apiVersion: v1
kind: Service
metadata:
  name: casestudy-jenkins1
spec:
  type: NodePort
  selector:
    app: casestudy-jenkins1
  ports:
    - port: 80
      targetPort: 80     
      nodePort: 30001    
